# Getting started with TinyTimeMixer (TTM)

This notebooke demonstrates the usage of a pre-trained `TinyTimeMixer` model for several multivariate time series forecasting tasks. For details related to model architecture, refer to the [TTM paper](https://arxiv.org/pdf/2401.03955.pdf).

In this example, we will use a pre-trained TTM-512-96 model. That means the TTM model can take an input of 512 time points (`context_length`), and can forecast upto 96 time points (`forecast_length`) in the future. We will use the pre-trained TTM in two settings:
1. **Zero-shot**: The pre-trained TTM will be directly used to evaluate on the `test` split of the target data. Note that the TTM was NOT pre-trained on the target data.
2. **Few-shot**: The pre-trained TTM will be quickly fine-tuned on only 5% of the `train` split of the target data, and subsequently, evaluated on the `test` part of the target data.

Note: Alternatively, this notebook can be modified to try any other TTM model from a suite of TTM models. For details, visit the [Hugging Face TTM Model Repository](https://huggingface.co/ibm-granite/granite-timeseries-ttm-r2).

1. IBM Granite TTM-R1 pre-trained models can be found here: [Granite-TTM-R1 Model Card](https://huggingface.co/ibm-granite/granite-timeseries-ttm-r1)
2. IBM Granite TTM-R2 pre-trained models can be found here: [Granite-TTM-R2 Model Card](https://huggingface.co/ibm-granite/granite-timeseries-ttm-r2)
3. Research-use (non-commercial use only) TTM-R2 pre-trained models can be found here: [Research-Use-TTM-R2](https://huggingface.co/ibm-research/ttm-research-r2)

### The get_model() utility
TTM Model card offers a suite of models with varying `context_length` and `prediction_length` combinations.
In this notebook, we will utilize the TSFM `get_model()` utility that automatically selects the right model based on the given input `context_length` and `prediction_length` (and some other optional arguments) abstracting away the internal complexity. See the usage examples below in the `zeroshot_eval()` and `fewshot_finetune_eval()` functions. For more details see the [docstring](https://github.com/ibm-granite/granite-tsfm/blob/main/tsfm_public/toolkit/get_model.py) of the function definition.

## Install `tsfm` 
**[Optional for Local Run / Mandatory for Google Colab]**  
Run the below cell to install `tsfm`. Skip if already installed.

In [9]:
# # Install the tsfm library
# ! pip install "granite-tsfm[notebooks] @ git+https://github.com/ibm-granite/granite-tsfm.git@v0.3.3"

## Imports

In [10]:
import math
import os
import tempfile

import pandas as pd
import numpy as np
from torch.optim import AdamW
from torch.optim.lr_scheduler import OneCycleLR
from transformers import EarlyStoppingCallback, Trainer, TrainingArguments, set_seed
from transformers.integrations import INTEGRATION_TO_CALLBACK

from tsfm_public import TimeSeriesPreprocessor, TrackingCallback, count_parameters, get_datasets
from tsfm_public.toolkit.get_model import get_model
from tsfm_public.toolkit.lr_finder import optimal_lr_finder
from tsfm_public.toolkit.visualization import plot_predictions
import warnings


# Suppress all warnings
warnings.filterwarnings("ignore")

In [11]:
OUT_DIR = "ttm_finetuned_models/t"

## Finetune evaluation method

In [12]:
def fewshot_finetune_eval(
    dataset_name,
    batch_size,
    data,
    learning_rate=None,
    context_length=512,
    forecast_length=96,
    fewshot_percent=5,
    freeze_backbone=True,
    num_epochs=50,
    save_dir=OUT_DIR,
    loss="mse",
    quantile=0.5,
):
    out_dir = os.path.join(save_dir, dataset_name)

    print("-" * 20, f"Running few-shot {fewshot_percent}%", "-" * 20)

    # Data prep: Get dataset

    tsp = TimeSeriesPreprocessor(
        **column_specifiers,
        context_length=context_length,
        prediction_length=forecast_length,
        scaling=True,
        encode_categorical=False,
        scaler_type="standard",
    )

    # change head dropout to 0.7 for ett datasets
    if "ett" in dataset_name:
        finetune_forecast_model = get_model(
            TTM_MODEL_PATH,
            context_length=context_length,
            prediction_length=forecast_length,
            freq_prefix_tuning=False,
            freq=None,
            prefer_l1_loss=False,
            prefer_longer_context=True,
            # Can also provide TTM Config args
            head_dropout=0.7,
            loss=loss,
            quantile=quantile,
        )
    else:
        finetune_forecast_model = get_model(
            TTM_MODEL_PATH,
            context_length=context_length,
            prediction_length=forecast_length,
            freq_prefix_tuning=False,
            freq=None,
            prefer_l1_loss=False,
            prefer_longer_context=True,
            # Can also provide TTM Config args
            loss=loss,
            quantile=quantile,
        )

    dset_train, dset_val, dset_test = get_datasets(
        tsp,
        data,
        split_config,
        fewshot_fraction=fewshot_percent / 100,
        fewshot_location="first",
        use_frequency_token=finetune_forecast_model.config.resolution_prefix_tuning,
    )

    if freeze_backbone:
        print(
            "Number of params before freezing backbone",
            count_parameters(finetune_forecast_model),
        )

        # Freeze the backbone of the model
        for param in finetune_forecast_model.backbone.parameters():
            param.requires_grad = False

        # Count params
        print(
            "Number of params after freezing the backbone",
            count_parameters(finetune_forecast_model),
        )

    # Find optimal learning rate
    # Use with caution: Set it manually if the suggested learning rate is not suitable
    if learning_rate is None:
        learning_rate, finetune_forecast_model = optimal_lr_finder(
            finetune_forecast_model,
            dset_train,
            batch_size=batch_size,
        )
        print("OPTIMAL SUGGESTED LEARNING RATE =", learning_rate)

    print(f"Using learning rate = {learning_rate}")
    finetune_forecast_args = TrainingArguments(
        output_dir=os.path.join(out_dir, "output"),
        overwrite_output_dir=True,
        learning_rate=learning_rate,
        num_train_epochs=num_epochs,
        do_eval=True,
        eval_strategy="epoch",
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        dataloader_num_workers=8,
        report_to="none",
        save_strategy="epoch",
        logging_strategy="epoch",
        save_total_limit=1,
        logging_dir=os.path.join(out_dir, "logs"),  # Make sure to specify a logging directory
        load_best_model_at_end=True,  # Load the best model when training ends
        metric_for_best_model="eval_loss",  # Metric to monitor for early stopping
        greater_is_better=False,  # For loss
        seed=SEED,
    )

    # Create the early stopping callback
    early_stopping_callback = EarlyStoppingCallback(
        early_stopping_patience=10,  # Number of epochs with no improvement after which to stop
        early_stopping_threshold=1e-5,  # Minimum improvement required to consider as improvement
    )
    tracking_callback = TrackingCallback()

    # Optimizer and scheduler
    optimizer = AdamW(finetune_forecast_model.parameters(), lr=learning_rate)
    scheduler = OneCycleLR(
        optimizer,
        learning_rate,
        epochs=num_epochs,
        steps_per_epoch=math.ceil(len(dset_train) / (batch_size)),
    )

    finetune_forecast_trainer = Trainer(
        model=finetune_forecast_model,
        args=finetune_forecast_args,
        train_dataset=dset_train,
        eval_dataset=dset_val,
        callbacks=[early_stopping_callback, tracking_callback],
        optimizers=(optimizer, scheduler),
    )
    finetune_forecast_trainer.remove_callback(INTEGRATION_TO_CALLBACK["codecarbon"])

    # Fine tune
    finetune_forecast_trainer.train()

    # Evaluation
    print("+" * 20, f"Test MSE after few-shot {fewshot_percent}% fine-tuning", "+" * 20)

    finetune_forecast_trainer.model.loss = "mse"  # fixing metric to mse for evaluation

    fewshot_output = finetune_forecast_trainer.evaluate(dset_test)
    print(fewshot_output)
    # print("+" * 60)

    # get predictions

    predictions_dict = finetune_forecast_trainer.predict(dset_test)

    predictions_np = predictions_dict.predictions[0]

    print(predictions_np.shape)

    # get backbone embeddings (if needed for further analysis)

    backbone_embedding = predictions_dict.predictions[1]

    # print(backbone_embedding.shape)
    return dset_test, predictions_np
    # # plot
    # plot_predictions(
    #     model=finetune_forecast_trainer.model,
    #     dset=dset_test,
    #     plot_dir=os.path.join(OUT_DIR, dataset_name),
    #     plot_prefix="test_fewshot",
    #     indices=[685, 118, 902, 1984, 894, 967, 304, 57, 265, 1015],
    #     channel=0,
    # )

In [13]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def calculate_metrics(dset_test, preds, model_name="Model",):
    """
    Calculate comprehensive evaluation metrics.
    
    Args:
        dset_test: Test dataset
        preds: Predictions array
        model_name: Name to display in output
    
    Returns:
        dict: Dictionary containing all metrics
    
    Notes:
        MASE: Scaled against the naive 1-step forecast error (mean |y_t - y_{t-1}|)
              computed from the context window (past_values).
        CRPS: For a deterministic/point forecast, CRPS == MAE. Install
              `properscoring` and pass forecast samples/distributions for a 
              proper probabilistic CRPS.
    """
    # Extract ground truth and past values from dset_test
    y_true_list = []
    past_list = []
    for i in range(len(dset_test)):
        sample = dset_test[i]
        
        future_values = sample['future_values']
        if hasattr(future_values, "detach"):
            future_values = future_values.detach().cpu().numpy()
        else:
            future_values = np.asarray(future_values)
        y_true_list.append(future_values)
        
        past_values = sample['past_values']
        if hasattr(past_values, "detach"):
            past_values = past_values.detach().cpu().numpy()
        else:
            past_values = np.asarray(past_values)
        past_list.append(past_values)
    
    y_true = np.array(y_true_list)   # (samples, forecast_len, channels)
    past_arr = np.array(past_list)   # (samples, context_len, channels)
    
    # Validate shapes match
    if preds.shape != y_true.shape:
        raise ValueError(f"Shape mismatch! Predictions: {preds.shape}, Ground truth: {y_true.shape}")
    
    # Flatten for overall metric calculations
    y_true_flat = y_true.flatten()
    preds_flat = preds.flatten()
    epsilon = 1e-8
    
    # Overall metrics
    mse   = float(mean_squared_error(y_true_flat, preds_flat))
    rmse  = float(np.sqrt(mse))
    mae   = float(mean_absolute_error(y_true_flat, preds_flat))
    mape  = float(np.mean(np.abs((y_true_flat - preds_flat) / (y_true_flat + epsilon))) * 100)
    r2    = float(r2_score(y_true_flat, preds_flat))
    smape = float(np.mean(2.0 * np.abs(preds_flat - y_true_flat) / (np.abs(preds_flat) + np.abs(y_true_flat) + epsilon)) * 100)
    
    # MASE: naive 1-step scale from context window
    # naive_scale = mean |y_t - y_{t-1}| over all samples and channels
    naive_scale_overall = float(np.mean(np.abs(np.diff(past_arr, axis=1))) + epsilon)
    mase = mae / naive_scale_overall
    
    # CRPS (deterministic): equals MAE for point forecasts
    crps = mae
    
    # Per-channel metrics
    num_samples, num_timesteps, num_channels = y_true.shape
    
    per_channel_metrics = {}
    for channel in range(num_channels):
        channel_name = target_columns[channel] if channel < len(target_columns) else f"Channel {channel}"
        
        y_true_channel = y_true[:, :, channel].flatten()
        preds_channel  = preds[:, :, channel].flatten()
        
        ch_mse   = float(mean_squared_error(y_true_channel, preds_channel))
        ch_rmse  = float(np.sqrt(ch_mse))
        ch_mae   = float(mean_absolute_error(y_true_channel, preds_channel))
        ch_mape  = float(np.mean(np.abs((y_true_channel - preds_channel) / (y_true_channel + epsilon))) * 100)
        ch_r2    = float(r2_score(y_true_channel, preds_channel))
        ch_smape = float(np.mean(2.0 * np.abs(preds_channel - y_true_channel) / (np.abs(preds_channel) + np.abs(y_true_channel) + epsilon)) * 100)
        
        # Per-channel MASE: scale from that channel's context differences
        ch_naive_scale = float(np.mean(np.abs(np.diff(past_arr[:, :, channel], axis=1))) + epsilon)
        ch_mase = ch_mae / ch_naive_scale
        
        # CRPS (point forecast) = MAE per channel
        ch_crps = ch_mae
        
        per_channel_metrics[channel_name] = {
            'mse':   ch_mse,
            'rmse':  ch_rmse,
            'mae':   ch_mae,
            'mape':  ch_mape,
            'r2':    ch_r2,
            'smape': ch_smape,
            'mase':  ch_mase,
            'crps':  ch_crps,
        }
    
    return {
        'overall': {
            'mse':   mse,
            'rmse':  rmse,
            'mae':   mae,
            'mape':  mape,
            'r2':    r2,
            'smape': smape,
            'mase':  mase,
            'crps':  crps,
        },
        'per_channel': per_channel_metrics
    }

# Calculate metrics for TTM predictions
# ttm_metrics = calculate_metrics(dset_test, preds, model_name="TTM Zero-Shot")

In [14]:
def calculate_baseline_metrics(dset, method='mean'):
    """
    Calculate baseline metrics using simple statistical methods.
    
    Args:
        dset: Dataset containing past_values and future_values
        method: 'mean' or 'median' - aggregation method for baseline
    
    Returns:
        tuple: (predictions array, metrics dictionary)
    """
    preds = []
    y_true_list = []
    past_list = []
    
    for i in range(len(dset)):
        past_values = dset[i]['past_values']
        if hasattr(past_values, "detach"):
            past = past_values.detach().cpu().numpy()
        else:
            past = np.asarray(past_values)
        past_list.append(past)
        
        if method == 'mean':
            baseline_value = np.mean(past, axis=0)
        elif method == 'median':
            baseline_value = np.median(past, axis=0)
        else:
            raise ValueError(f"Unknown method: {method}. Use 'mean' or 'median'")
        
        pred = np.tile(baseline_value, (PREDICTION_LENGTH, 1))
        preds.append(pred)

        future_values = dset[i]['future_values']
        if hasattr(future_values, "detach"):
            future_values = future_values.detach().cpu().numpy()
        else:
            future_values = np.asarray(future_values)
        y_true_list.append(future_values)
    
    y_true = np.array(y_true_list)
    preds = np.array(preds)
    past_arr = np.array(past_list)   # (samples, context_len, channels)
    
    # Validate shapes match
    if preds.shape != y_true.shape:
        raise ValueError(f"Shape mismatch! Predictions: {preds.shape}, Ground truth: {y_true.shape}")
    
    # Calculate overall metrics
    y_true_flat = y_true.flatten()
    preds_flat = preds.flatten()
    epsilon = 1e-8
    
    mse = float(mean_squared_error(y_true_flat, preds_flat))
    rmse = float(np.sqrt(mse))
    mae = float(mean_absolute_error(y_true_flat, preds_flat))
    mape = float(np.mean(np.abs((y_true_flat - preds_flat) / (y_true_flat + epsilon))) * 100)
    r2 = float(r2_score(y_true_flat, preds_flat))
    smape = float(np.mean(2.0 * np.abs(preds_flat - y_true_flat) / (np.abs(preds_flat) + np.abs(y_true_flat) + epsilon)) * 100)

    # Overall MASE and CRPS (same approach as TTM metrics)
    naive_scale_overall = float(np.mean(np.abs(np.diff(past_arr, axis=1))) + epsilon)
    mase = mae / naive_scale_overall
    crps = mae
    
    # Calculate per-channel metrics
    num_samples, num_timesteps, num_channels = y_true.shape
    
    per_channel_metrics = {}
    for channel in range(num_channels):
        channel_name = target_columns[channel] if channel < len(target_columns) else f"Channel {channel}"
        
        # Extract channel data
        y_true_channel = y_true[:, :, channel].flatten()
        preds_channel = preds[:, :, channel].flatten()
        
        # Calculate metrics for this channel
        ch_mse = float(mean_squared_error(y_true_channel, preds_channel))
        ch_rmse = float(np.sqrt(ch_mse))
        ch_mae = float(mean_absolute_error(y_true_channel, preds_channel))
        ch_mape = float(np.mean(np.abs((y_true_channel - preds_channel) / (y_true_channel + epsilon))) * 100)
        ch_r2 = float(r2_score(y_true_channel, preds_channel))
        ch_smape = float(np.mean(2.0 * np.abs(preds_channel - y_true_channel) / (np.abs(preds_channel) + np.abs(y_true_channel) + epsilon)) * 100)
        
        # Per-channel MASE: scale from that channel's context differences
        ch_naive_scale = float(np.mean(np.abs(np.diff(past_arr[:, :, channel], axis=1))) + epsilon)
        ch_mase = ch_mae / ch_naive_scale
        
        # CRPS (point forecast) = MAE per channel
        ch_crps = ch_mae
        
        per_channel_metrics[channel_name] = {
            'mse': ch_mse,
            'rmse': ch_rmse,
            'mae': ch_mae,
            'mape': ch_mape,
            'r2': ch_r2,
            'smape': ch_smape,
            'mase': ch_mase,
            'crps': ch_crps,
        }
    
    metrics = {
        'overall': {
            'mse': mse,
            'rmse': rmse,
            'mae': mae,
            'mape': mape,
            'r2': r2,
            'smape': smape,
            'mase': mase,
            'crps': crps,
        },
        'per_channel': per_channel_metrics
    }
    
    return preds, metrics


# Calculate baseline metrics
# mean_baseline_preds, mean_baseline_metrics = calculate_baseline_metrics(dset_test, method='mean')
# median_baseline_preds, median_baseline_metrics = calculate_baseline_metrics(dset_test, method='median')

In [15]:
SEED = 42
set_seed(SEED)

# TTM Model path. The default model path is Granite-R2. Below, you can choose other TTM releases.
TTM_MODEL_PATH = "ibm-granite/granite-timeseries-ttm-r2"
# TTM_MODEL_PATH = "ibm-granite/granite-timeseries-ttm-r1"
# TTM_MODEL_PATH = "ibm-research/ttm-research-r2"

# Context length, Or Length of the history.
# Currently supported values are: 512/1024/1536 for Granite-TTM-R2 and Research-Use-TTM-R2, and 512/1024 for Granite-TTM-R1
CONTEXT_LENGTH = 512
#1  week or 2 weeks, predict for next 2 days
# Granite-TTM-R2 supports forecast length upto 720 and Granite-TTM-R1 supports forecast length upto 96
# Arima? Rolling average, Rolling median 
PREDICTION_LENGTH = 96
OUT_DIR = "ttm_finetuned_models/"

In [16]:
import json
from datetime import datetime
from tqdm import tqdm

folder = r"/home/rishi/ML Projects/Air Pollution/CPCB/sites_imputed"
files = os.listdir(folder)  # Fixed - get all files in the folder
timestamp_column = "Timestamp"
id_columns = []  # mention the ids that uniquely identify a time-series.

target_columns = [
 'PM2.5 (µg/m³)',
 'PM10 (µg/m³)',
 'NO2 (µg/m³)',
 'SO2 (µg/m³)',
 'CO (mg/m³)',
 'Ozone (µg/m³)',
]

split_config = {
    "train": 0.6,
    "test": 0.2,
}

column_specifiers = {
    "timestamp_column": timestamp_column,
    "id_columns": id_columns,
    "target_columns": target_columns,
    "control_columns": [],
}

# Create output directory for results
results_dir = "ttm_finetuning_results_mase"
os.makedirs(results_dir, exist_ok=True)

# Store all results
all_results = []

for file in tqdm(files):
    if not file.endswith('.csv'):
        continue
        
    print(f"\n{'='*60}")
    print(f"Processing: {file}")
    print(f"{'='*60}")
    
    try:
        data = pd.read_csv(
            os.path.join(folder, file),
            parse_dates=[timestamp_column],
        ).copy()
        
        site_name = file.replace('.csv', '')
        
        # Run zero-shot evaluation
        dset_test, preds = fewshot_finetune_eval(
            dataset_name=site_name, 
            data=data,
            context_length=CONTEXT_LENGTH, 
            forecast_length=PREDICTION_LENGTH, 
            batch_size=64
        )
        
        # Calculate TTM metrics
        ttm_metrics = calculate_metrics(dset_test, preds, model_name=f"TTM - {site_name}")
        
        # Calculate baseline metrics (mean)
        mean_baseline_preds, mean_baseline_metrics = calculate_baseline_metrics(dset=dset_test, method='mean')
        
        # Calculate baseline metrics (median)
        median_baseline_preds, median_baseline_metrics = calculate_baseline_metrics(dset=dset_test, method='median')
        
        # Store results
        result = {
            'site': site_name,
            'file': file,
            'timestamp': datetime.now().isoformat(),
            'context_length': CONTEXT_LENGTH,
            'prediction_length': PREDICTION_LENGTH,
            'ttm_metrics': ttm_metrics,
            'mean_baseline_metrics': mean_baseline_metrics,
            'median_baseline_metrics': median_baseline_metrics
        }
        all_results.append(result)
        
        # Save individual site results
        site_result_file = os.path.join(results_dir, f"{site_name}_metrics.json")
        with open(site_result_file, 'w') as f:
            json.dump(result, f, indent=2)
        print(f"Saved results to: {site_result_file}")
        
    except Exception as e:
        print(f"Error processing {file}: {str(e)}")
        continue

# Save combined results
combined_results_file = os.path.join(results_dir, f"all_sites_metrics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json")
with open(combined_results_file, 'w') as f:
    json.dump(all_results, f, indent=2)
print(f"\n{'='*60}")
print(f"All results saved to: {combined_results_file}")
print(f"{'='*60}")

  0%|          | 0/138 [00:00<?, ?it/s]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

============================================================
Processing: site_1431_Patparganj_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.4384747418490323 seconds, Total Train Time = 11.068474054336548
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4741712510585785, 'eval_runtime': 0.5791, 'eval_samples_per_second': 8919.267, 'eval_steps_per_second': 139.876, 'epoch': 11.0}
(5165, 96, 6)

  1%|          | 1/138 [00:17<39:58, 17.51s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1431_Patparganj_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5334_Polayathode_Kollam_Kerala_PCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000298364724028334

OPTIMAL SUGGESTED LEARNING RATE = 0.000298364724028334
Using learning rate = 0.000298364724028334

[TrackingCallback] Mean Epoch Time = 0.2570584470575506 seconds, Total Train Time = 8.906402587890625
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4466733932495117, 'eval_runtime': 0.5166, 'eval_samples_per_second': 9998.897, 'eval_steps_per_second': 156.807, 'epoch': 11.0}
(5165, 96, 6)

  1%|▏         | 2/138 [00:32<36:22, 16.05s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5334_Polayathode_Kollam_Kerala_PCB_15Min_metrics.json

============================================================
Processing: site_5472_Madan_Mohan_Malaviya_University_of_Technology_Gorakhpur_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.25715498490767047 seconds, Total Train Time = 10.989607095718384
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6648091673851013, 'eval_runtime': 0.513, 'eval_samples_per_second': 10068.736, 'eval_steps_per_second': 157.903, 'epoch': 11.0}
(5165, 96, 6)

  2%|▏         | 3/138 [00:49<37:02, 16.46s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5472_Madan_Mohan_Malaviya_University_of_Technology_Gorakhpur_UPPCB_15Min_metrics.json

============================================================
Processing: site_5667_Deen_Dayal_Nagar_Gwalior_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2734148719094016 seconds, Total Train Time = 9.789353847503662
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3892097771167755, 'eval_runtime': 0.5659, 'eval_samples_per_second': 9127.707, 'eval_steps_per_second': 143.145, 'epoch': 11.0}
(5165, 96, 6)

  3%|▎         | 4/138 [01:05<36:13, 16.22s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5667_Deen_Dayal_Nagar_Gwalior_MPPCB_15Min_metrics.json

============================================================
Processing: site_5613_Transport_Nagar_Moradabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.2734566529591878 seconds, Total Train Time = 12.593853235244751
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4419213831424713, 'eval_runtime': 0.56, 'eval_samples_per_second': 9223.596, 'eval_steps_per_second': 144.649, 'epoch': 12.0}
(5165, 96, 6)

  4%|▎         | 5/138 [01:24<38:03, 17.17s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5613_Transport_Nagar_Moradabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_1422_Dwarka-Sector_8_Delhi_DPCC__15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.254764816977761 seconds, Total Train Time = 8.97475290298462
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.8670780062675476, 'eval_runtime': 0.554, 'eval_samples_per_second': 9323.295, 'eval_steps_per_second': 146.212, 'epoch': 11.0}
(5165, 96, 6)

  4%|▍         | 6/138 [01:39<36:28, 16.58s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1422_Dwarka-Sector_8_Delhi_DPCC__15Min_metrics.json

============================================================
Processing: site_277_Lalbagh_Lucknow_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.24675293402238327 seconds, Total Train Time = 11.064483642578125
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.571442186832428, 'eval_runtime': 0.5301, 'eval_samples_per_second': 9743.631, 'eval_steps_per_second': 152.804, 'epoch': 11.0}
(5165, 96, 6)

  5%|▌         | 7/138 [01:56<36:27, 16.70s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_277_Lalbagh_Lucknow_CPCB_15Min_metrics.json

============================================================
Processing: site_5538_New_DM_Office_Arrah_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.24216077544472434 seconds, Total Train Time = 8.41854190826416
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.08313709497451782, 'eval_runtime': 0.4768, 'eval_samples_per_second': 10832.841, 'eval_steps_per_second': 169.886, 'epoch': 11.0}
(5165, 96, 6)

  6%|▌         | 8/138 [02:10<34:34, 15.95s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5538_New_DM_Office_Arrah_BSPCB_15Min_metrics.json

============================================================
Processing: site_5537_Employment_Office_Moradabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.2524448308077725 seconds, Total Train Time = 8.76786208152771
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3936608135700226, 'eval_runtime': 2.6795, 'eval_samples_per_second': 1927.565, 'eval_steps_per_second': 30.229, 'epoch': 11.0}
(5165, 96, 6)

  7%|▋         | 9/138 [02:27<35:02, 16.30s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5537_Employment_Office_Moradabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_1429_Nehru_Nagar_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.24218470400029962 seconds, Total Train Time = 8.442144393920898
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6428765058517456, 'eval_runtime': 0.4978, 'eval_samples_per_second': 10376.585, 'eval_steps_per_second': 162.731, 'epoch': 11.0}
(5165, 96, 6)

  7%|▋         | 10/138 [02:42<33:20, 15.63s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1429_Nehru_Nagar_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5490_Town_Hall_Munger_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.24886657641484186 seconds, Total Train Time = 10.436367750167847
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.18797767162322998, 'eval_runtime': 0.5113, 'eval_samples_per_second': 10101.351, 'eval_steps_per_second': 158.414, 'epoch': 13.0}
(5165, 96, 6)

  8%|▊         | 11/138 [03:00<34:54, 16.49s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5490_Town_Hall_Munger_BSPCB_15Min_metrics.json

============================================================
Processing: site_1423_Jahangirpuri_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.24375369332053445 seconds, Total Train Time = 8.794007062911987
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.559105396270752, 'eval_runtime': 0.4665, 'eval_samples_per_second': 11072.229, 'eval_steps_per_second': 173.64, 'epoch': 11.0}
(5165, 96, 6)

  9%|▊         | 12/138 [03:15<33:26, 15.92s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1423_Jahangirpuri_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_1428_Okhla_Phase-2_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.24607552181590686 seconds, Total Train Time = 8.709902286529541
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.48241904377937317, 'eval_runtime': 0.5451, 'eval_samples_per_second': 9475.372, 'eval_steps_per_second': 148.597, 'epoch': 11.0}
(5165, 96, 6)

  9%|▉         | 13/138 [03:29<32:18, 15.51s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1428_Okhla_Phase-2_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_118_DTU_Delhi_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.249830961227417 seconds, Total Train Time = 8.760067224502563
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3922129273414612, 'eval_runtime': 0.5131, 'eval_samples_per_second': 10065.709, 'eval_steps_per_second': 157.855, 'epoch': 11.0}
(5165, 96, 6)

 10%|█         | 14/138 [03:46<32:41, 15.82s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_118_DTU_Delhi_CPCB_15Min_metrics.json

============================================================
Processing: site_5602_Ramachandrapuram_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.24379799582741477 seconds, Total Train Time = 8.73301649093628
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.9342618584632874, 'eval_runtime': 0.5544, 'eval_samples_per_second': 9317.088, 'eval_steps_per_second': 146.115, 'epoch': 11.0}
(5165, 96, 6)

 11%|█         | 15/138 [04:00<31:43, 15.47s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5602_Ramachandrapuram_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_5603_Kalindi_Kunj_Khurja_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.45135159925981 seconds, Total Train Time = 10.91499924659729
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.9792282581329346, 'eval_runtime': 0.5454, 'eval_samples_per_second': 9469.817, 'eval_steps_per_second': 148.51, 'epoch': 11.0}
(5165, 96, 6)

 12%|█▏        | 16/138 [04:17<32:09, 15.82s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5603_Kalindi_Kunj_Khurja_UPPCB_15Min_metrics.json

============================================================
Processing: site_260_GVM_Corporation_Visakhapatnam_APPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.24569593157087052 seconds, Total Train Time = 11.166414022445679
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.9533615112304688, 'eval_runtime': 0.5595, 'eval_samples_per_second': 9232.11, 'eval_steps_per_second': 144.782, 'epoch': 14.0}
(5165, 96, 6)

 12%|█▏        | 17/138 [04:34<32:32, 16.14s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_260_GVM_Corporation_Visakhapatnam_APPCB_15Min_metrics.json

============================================================
Processing: site_5463_Shastripuram_Agra_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.2560827081853693 seconds, Total Train Time = 11.111118078231812
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.300568699836731, 'eval_runtime': 0.52, 'eval_samples_per_second': 9933.148, 'eval_steps_per_second': 155.776, 'epoch': 11.0}
(5165, 96, 6)

 13%|█▎        | 18/138 [04:51<32:46, 16.39s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5463_Shastripuram_Agra_UPPCB_15Min_metrics.json

============================================================
Processing: site_1406_Secretariat_Amaravati_APPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.24254744703119452 seconds, Total Train Time = 8.597213745117188
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.9345302581787109, 'eval_runtime': 0.491, 'eval_samples_per_second': 10520.279, 'eval_steps_per_second': 164.984, 'epoch': 11.0}
(5165, 96, 6)

 14%|█▍        | 19/138 [05:05<31:23, 15.83s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1406_Secretariat_Amaravati_APPCB_15Min_metrics.json

============================================================
Processing: site_1561_Mundka_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.4557189507917924 seconds, Total Train Time = 11.173079013824463
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6539298892021179, 'eval_runtime': 0.527, 'eval_samples_per_second': 9800.631, 'eval_steps_per_second': 153.698, 'epoch': 11.0}
(5165, 96, 6)

 14%|█▍        | 20/138 [05:23<32:00, 16.28s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1561_Mundka_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5555_Jigar_Colony_Moradabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2310064055702903 seconds, Total Train Time = 8.226019144058228
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4819537401199341, 'eval_runtime': 0.5007, 'eval_samples_per_second': 10315.033, 'eval_steps_per_second': 161.765, 'epoch': 11.0}
(5165, 96, 6)

 15%|█▌        | 21/138 [05:37<30:21, 15.57s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5555_Jigar_Colony_Moradabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_309_Victoria_Kolkata_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.25325367667458276 seconds, Total Train Time = 8.748478889465332
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3646312355995178, 'eval_runtime': 0.5266, 'eval_samples_per_second': 9807.802, 'eval_steps_per_second': 153.811, 'epoch': 11.0}
(5165, 96, 6)

 16%|█▌        | 22/138 [05:54<31:00, 16.04s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_309_Victoria_Kolkata_WBPCB_15Min_metrics.json

============================================================
Processing: site_1563_Pusa_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2424990263852206 seconds, Total Train Time = 8.452092170715332
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5370227098464966, 'eval_runtime': 0.5026, 'eval_samples_per_second': 10276.792, 'eval_steps_per_second': 161.166, 'epoch': 11.0}
(5165, 96, 6)

 17%|█▋        | 23/138 [06:08<29:42, 15.50s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1563_Pusa_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5459_Motilal_Nehru_NIT_Prayagraj_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.23918936469338156 seconds, Total Train Time = 8.575708150863647
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4069611132144928, 'eval_runtime': 0.5427, 'eval_samples_per_second': 9517.784, 'eval_steps_per_second': 149.262, 'epoch': 11.0}
(5165, 96, 6)

 17%|█▋        | 24/138 [06:25<30:06, 15.84s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5459_Motilal_Nehru_NIT_Prayagraj_UPPCB_15Min_metrics.json

============================================================
Processing: site_300_Priyambada_Housing_Estate_Haldia_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.25198921290310944 seconds, Total Train Time = 8.795578718185425
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4824635088443756, 'eval_runtime': 0.6342, 'eval_samples_per_second': 8144.503, 'eval_steps_per_second': 127.726, 'epoch': 11.0}
(5165, 96, 6)

 18%|█▊        | 25/138 [06:40<29:25, 15.63s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_300_Priyambada_Housing_Estate_Haldia_WBPCB_15Min_metrics.json

============================================================
Processing: site_1396_Shastri_Nagar_Jaipur_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.26554515145041724 seconds, Total Train Time = 9.242061853408813
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.9969149231910706, 'eval_runtime': 0.6808, 'eval_samples_per_second': 7586.241, 'eval_steps_per_second': 118.971, 'epoch': 11.0}
(5165, 96, 6)

 19%|█▉        | 26/138 [06:56<29:24, 15.75s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1396_Shastri_Nagar_Jaipur_RSPCB_15Min_metrics.json

============================================================
Processing: site_5129_Bidhannagar_Kolkata_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.2652664401314475 seconds, Total Train Time = 9.117415428161621
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4119623601436615, 'eval_runtime': 0.5457, 'eval_samples_per_second': 9464.542, 'eval_steps_per_second': 148.427, 'epoch': 11.0}
(5165, 96, 6)

 20%|█▉        | 27/138 [07:14<30:12, 16.33s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5129_Bidhannagar_Kolkata_WBPCB_15Min_metrics.json

============================================================
Processing: site_5024_Alipur_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.2596406936645508 seconds, Total Train Time = 9.031242847442627
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4163967967033386, 'eval_runtime': 0.5503, 'eval_samples_per_second': 9386.609, 'eval_steps_per_second': 147.205, 'epoch': 11.0}
(5165, 96, 6)

 20%|██        | 28/138 [07:29<29:12, 15.93s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5024_Alipur_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_122_Mandir_Marg_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.28218386389992456 seconds, Total Train Time = 11.618011474609375
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.8695697784423828, 'eval_runtime': 0.5279, 'eval_samples_per_second': 9783.657, 'eval_steps_per_second': 153.432, 'epoch': 11.0}
(5165, 96, 6)

 21%|██        | 29/138 [07:46<29:51, 16.43s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_122_Mandir_Marg_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5661_Maharaj_Bada_Gwalior_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2649628899314187 seconds, Total Train Time = 9.227346897125244
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.39238980412483215, 'eval_runtime': 0.551, 'eval_samples_per_second': 9373.276, 'eval_steps_per_second': 146.996, 'epoch': 11.0}
(5165, 96, 6)

 22%|██▏       | 30/138 [08:02<29:07, 16.18s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5661_Maharaj_Bada_Gwalior_MPPCB_15Min_metrics.json

============================================================
Processing: site_5546_Mirchaibari_Katihar_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.49282544309442694 seconds, Total Train Time = 11.924319505691528
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.18251051008701324, 'eval_runtime': 0.506, 'eval_samples_per_second': 10206.86, 'eval_steps_per_second': 160.069, 'epoch': 11.0}
(5165, 96, 6)

 22%|██▏       | 31/138 [08:20<29:44, 16.68s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5546_Mirchaibari_Katihar_BSPCB_15Min_metrics.json

============================================================
Processing: site_5543_DM_Office_Kachari_Chowk_Bhagalpur_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2660766298120672 seconds, Total Train Time = 9.415392398834229
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.22837679088115692, 'eval_runtime': 0.5035, 'eval_samples_per_second': 10257.955, 'eval_steps_per_second': 160.87, 'epoch': 11.0}
(5165, 96, 6)

 23%|██▎       | 32/138 [08:35<28:46, 16.29s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5543_DM_Office_Kachari_Chowk_Bhagalpur_BSPCB_15Min_metrics.json

============================================================
Processing: site_114_IHBAS_Dilshad_Garden_Delhi_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.46066310188987036 seconds, Total Train Time = 11.542293787002563
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5417184233665466, 'eval_runtime': 0.5294, 'eval_samples_per_second': 9755.733, 'eval_steps_per_second': 152.994, 'epoch': 11.0}
(5165, 96, 6)

 24%|██▍       | 33/138 [08:53<29:22, 16.78s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_114_IHBAS_Dilshad_Garden_Delhi_CPCB_15Min_metrics.json

============================================================
Processing: site_5082_Indirapuram_Ghaziabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.25490318645130505 seconds, Total Train Time = 8.794783592224121
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.7004638910293579, 'eval_runtime': 0.5737, 'eval_samples_per_second': 9002.646, 'eval_steps_per_second': 141.184, 'epoch': 11.0}
(5165, 96, 6)

 25%|██▍       | 34/138 [09:08<28:09, 16.25s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5082_Indirapuram_Ghaziabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_296_Rabindra_Bharati_University_Kolkata_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2828028400739034 seconds, Total Train Time = 12.974912166595459
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5612697601318359, 'eval_runtime': 0.5121, 'eval_samples_per_second': 10085.062, 'eval_steps_per_second': 158.159, 'epoch': 12.0}
(5165, 96, 6)

 25%|██▌       | 35/138 [09:27<29:24, 17.13s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_296_Rabindra_Bharati_University_Kolkata_WBPCB_15Min_metrics.json

============================================================
Processing: site_1394_Shrinath_Puram_Kota_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.25973194295709784 seconds, Total Train Time = 9.004881620407104
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6051953434944153, 'eval_runtime': 0.5204, 'eval_samples_per_second': 9924.62, 'eval_steps_per_second': 155.643, 'epoch': 11.0}
(5165, 96, 6)

 26%|██▌       | 36/138 [09:42<28:04, 16.52s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1394_Shrinath_Puram_Kota_RSPCB_15Min_metrics.json

============================================================
Processing: site_1556_Jayanagar_5th_Block_Bengaluru_KSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.27665860002691095 seconds, Total Train Time = 11.775641679763794
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.1565489768981934, 'eval_runtime': 0.5564, 'eval_samples_per_second': 9282.117, 'eval_steps_per_second': 145.567, 'epoch': 11.0}
(5165, 96, 6)

 27%|██▋       | 37/138 [10:00<28:27, 16.91s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1556_Jayanagar_5th_Block_Bengaluru_KSPCB_15Min_metrics.json

============================================================
Processing: site_1397_Ashok_Nagar_Udaipur_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.26026656410910864 seconds, Total Train Time = 9.157495737075806
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5098214149475098, 'eval_runtime': 0.5314, 'eval_samples_per_second': 9720.351, 'eval_steps_per_second': 152.439, 'epoch': 11.0}
(5165, 96, 6)

 28%|██▊       | 38/138 [10:15<27:20, 16.40s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1397_Ashok_Nagar_Udaipur_RSPCB_15Min_metrics.json

============================================================
Processing: site_5500_FTI_Kidwai_Nagar_Kanpur_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.4809334711595015 seconds, Total Train Time = 11.785165309906006
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3779090344905853, 'eval_runtime': 0.6306, 'eval_samples_per_second': 8191.052, 'eval_steps_per_second': 128.456, 'epoch': 11.0}
(5165, 96, 6)

 28%|██▊       | 39/138 [10:34<28:02, 16.99s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5500_FTI_Kidwai_Nagar_Kanpur_UPPCB_15Min_metrics.json

============================================================
Processing: site_5262_Rajbansi_Nagar_Patna_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2588337768207897 seconds, Total Train Time = 8.975370407104492
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.23784197866916656, 'eval_runtime': 0.5284, 'eval_samples_per_second': 9774.321, 'eval_steps_per_second': 153.286, 'epoch': 11.0}
(5165, 96, 6)

 29%|██▉       | 40/138 [10:49<26:43, 16.36s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5262_Rajbansi_Nagar_Patna_BSPCB_15Min_metrics.json

============================================================
Processing: site_5675_Raghunathpali_Rourkela_OSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.25895964015613904 seconds, Total Train Time = 11.210604667663574
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.294773131608963, 'eval_runtime': 0.5246, 'eval_samples_per_second': 9845.797, 'eval_steps_per_second': 154.407, 'epoch': 11.0}
(5165, 96, 6)

 30%|██▉       | 41/138 [11:05<26:45, 16.55s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5675_Raghunathpali_Rourkela_OSPCB_15Min_metrics.json

============================================================
Processing: site_1438_Civil_Line_Jalandhar_PPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.2782841722170512 seconds, Total Train Time = 10.451317548751831
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.319225937128067, 'eval_runtime': 0.5486, 'eval_samples_per_second': 9414.535, 'eval_steps_per_second': 147.643, 'epoch': 12.0}
(5165, 96, 6)

 30%|███       | 42/138 [11:22<26:30, 16.57s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1438_Civil_Line_Jalandhar_PPCB_15Min_metrics.json

============================================================
Processing: site_5266_Vinoba_Nagara_Shivamogga_KSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.2602852257815274 seconds, Total Train Time = 11.298862218856812
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.0760157108306885, 'eval_runtime': 0.5561, 'eval_samples_per_second': 9287.792, 'eval_steps_per_second': 145.656, 'epoch': 11.0}
(5165, 96, 6)

 31%|███       | 43/138 [11:40<26:42, 16.86s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5266_Vinoba_Nagara_Shivamogga_KSPCB_15Min_metrics.json

============================================================
Processing: site_1393_Adarsh_Nagar_Jaipur_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.2624666889508565 seconds, Total Train Time = 10.08301854133606
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5520827770233154, 'eval_runtime': 0.5623, 'eval_samples_per_second': 9185.204, 'eval_steps_per_second': 144.047, 'epoch': 12.0}
(5165, 96, 6)

 32%|███▏      | 44/138 [11:56<26:13, 16.74s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1393_Adarsh_Nagar_Jaipur_RSPCB_15Min_metrics.json

============================================================
Processing: site_5650_Paryavaran_Parisar_Bhopal_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.26411624388261273 seconds, Total Train Time = 9.17877745628357
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.25768759846687317, 'eval_runtime': 0.5853, 'eval_samples_per_second': 8824.229, 'eval_steps_per_second': 138.386, 'epoch': 11.0}
(5165, 96, 6)

 33%|███▎      | 45/138 [12:12<25:22, 16.37s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5650_Paryavaran_Parisar_Bhopal_MPPCB_15Min_metrics.json

============================================================
Processing: site_1434_Wazirpur_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.5700870427218351 seconds, Total Train Time = 12.569743156433105
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.44612398743629456, 'eval_runtime': 0.5627, 'eval_samples_per_second': 9179.666, 'eval_steps_per_second': 143.96, 'epoch': 11.0}
(5165, 96, 6)

 33%|███▎      | 46/138 [12:30<26:09, 17.06s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1434_Wazirpur_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5656_Rampur_Korba_CECB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2638961718632625 seconds, Total Train Time = 10.801924467086792
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.8983226418495178, 'eval_runtime': 0.5619, 'eval_samples_per_second': 9192.294, 'eval_steps_per_second': 144.158, 'epoch': 13.0}
(5165, 96, 6)

 34%|███▍      | 47/138 [12:47<25:53, 17.07s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5656_Rampur_Korba_CECB_15Min_metrics.json

============================================================
Processing: site_5125_Hebbal_1st_Stage_Mysuru_KSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.271259605884552 seconds, Total Train Time = 12.28690242767334
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.1003522872924805, 'eval_runtime': 0.5137, 'eval_samples_per_second': 10054.469, 'eval_steps_per_second': 157.679, 'epoch': 12.0}
(5165, 96, 6)

 35%|███▍      | 48/138 [13:06<26:17, 17.53s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5125_Hebbal_1st_Stage_Mysuru_KSPCB_15Min_metrics.json

============================================================
Processing: site_136_Collectorate_Jodhpur_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.27620241858742456 seconds, Total Train Time = 9.508068323135376
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.48345473408699036, 'eval_runtime': 0.6352, 'eval_samples_per_second': 8130.903, 'eval_steps_per_second': 127.513, 'epoch': 11.0}
(5165, 96, 6)

 36%|███▌      | 49/138 [13:22<25:19, 17.07s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_136_Collectorate_Jodhpur_RSPCB_15Min_metrics.json

============================================================
Processing: site_5583_Shivaji_Nagar_Jhansi_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.28506610610268335 seconds, Total Train Time = 12.075149536132812
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.22641094028949738, 'eval_runtime': 0.6024, 'eval_samples_per_second': 8573.917, 'eval_steps_per_second': 134.46, 'epoch': 11.0}
(5165, 96, 6)

 36%|███▌      | 50/138 [13:41<25:46, 17.57s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5583_Shivaji_Nagar_Jhansi_UPPCB_15Min_metrics.json

============================================================
Processing: site_5261_Muradpur_Patna_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.27582801472056995 seconds, Total Train Time = 9.840903997421265
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.16057884693145752, 'eval_runtime': 0.5751, 'eval_samples_per_second': 8981.167, 'eval_steps_per_second': 140.847, 'epoch': 11.0}
(5165, 96, 6)

 37%|███▋      | 51/138 [13:57<24:48, 17.10s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5261_Muradpur_Patna_BSPCB_15Min_metrics.json

============================================================
Processing: site_5370_Buddha_Colony_Muzaffarpur_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.26076782833446155 seconds, Total Train Time = 11.205292701721191
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.2884596884250641, 'eval_runtime': 0.5098, 'eval_samples_per_second': 10131.922, 'eval_steps_per_second': 158.894, 'epoch': 11.0}
(5165, 96, 6)

 38%|███▊      | 52/138 [14:14<24:30, 17.10s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5370_Buddha_Colony_Muzaffarpur_BSPCB_15Min_metrics.json

============================================================
Processing: site_298_Zoo_Park_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.001917910261672489

OPTIMAL SUGGESTED LEARNING RATE = 0.001917910261672489
Using learning rate = 0.001917910261672489

[TrackingCallback] Mean Epoch Time = 0.2692942836067893 seconds, Total Train Time = 9.263940811157227
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4157915711402893, 'eval_runtime': 0.5194, 'eval_samples_per_second': 9943.662, 'eval_steps_per_second': 155.941, 'epoch': 11.0}
(5165, 96, 6)

 38%|███▊      | 53/138 [14:29<23:34, 16.64s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_298_Zoo_Park_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_274_Ghusuri_Howrah_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.260949351570823 seconds, Total Train Time = 9.002045631408691
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.7616138458251953, 'eval_runtime': 2.7758, 'eval_samples_per_second': 1860.74, 'eval_steps_per_second': 29.181, 'epoch': 11.0}
(5165, 96, 6)

 39%|███▉      | 54/138 [14:47<23:46, 16.99s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_274_Ghusuri_Howrah_WBPCB_15Min_metrics.json

============================================================
Processing: site_5460_B_R_Ambedkar_University_Lucknow_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.27698937329379 seconds, Total Train Time = 9.872069835662842
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.140306830406189, 'eval_runtime': 0.6395, 'eval_samples_per_second': 8076.307, 'eval_steps_per_second': 126.657, 'epoch': 11.0}
(5165, 96, 6)

 40%|███▉      | 55/138 [15:03<23:05, 16.70s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5460_B_R_Ambedkar_University_Lucknow_UPPCB_15Min_metrics.json

============================================================
Processing: site_5553_Chitragupta_Nagar_Siwan_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2756430886008523 seconds, Total Train Time = 9.682615041732788
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.20897723734378815, 'eval_runtime': 2.8261, 'eval_samples_per_second': 1827.615, 'eval_steps_per_second': 28.662, 'epoch': 11.0}
(5165, 96, 6)

 41%|████      | 56/138 [15:22<23:33, 17.24s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5553_Chitragupta_Nagar_Siwan_BSPCB_15Min_metrics.json

============================================================
Processing: site_5123_Sector-1_Noida_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.2692773125388406 seconds, Total Train Time = 9.482360601425171
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5739495754241943, 'eval_runtime': 0.5637, 'eval_samples_per_second': 9162.079, 'eval_steps_per_second': 143.684, 'epoch': 11.0}
(5165, 96, 6)

 41%|████▏     | 57/138 [15:38<22:41, 16.81s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5123_Sector-1_Noida_UPPCB_15Min_metrics.json

============================================================
Processing: site_5474_NSI_Kalyanpur_Kanpur_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.28532069379633124 seconds, Total Train Time = 9.597445487976074
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.8395209312438965, 'eval_runtime': 0.5874, 'eval_samples_per_second': 8792.591, 'eval_steps_per_second': 137.89, 'epoch': 11.0}
(5165, 96, 6)

 42%|████▏     | 58/138 [15:56<22:53, 17.17s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5474_NSI_Kalyanpur_Kanpur_UPPCB_15Min_metrics.json

============================================================
Processing: site_5484_Nagar_Nigam_Prayagraj_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2619120857932351 seconds, Total Train Time = 9.002657890319824
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4416642487049103, 'eval_runtime': 0.5314, 'eval_samples_per_second': 9718.981, 'eval_steps_per_second': 152.418, 'epoch': 11.0}
(5165, 96, 6)

 43%|████▎     | 59/138 [16:11<21:46, 16.54s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5484_Nagar_Nigam_Prayagraj_UPPCB_15Min_metrics.json

============================================================
Processing: site_5479_MIT-Daudpur_Kothi_Muzaffarpur_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.2665659745534261 seconds, Total Train Time = 14.507899045944214
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.21676887571811676, 'eval_runtime': 0.5486, 'eval_samples_per_second': 9414.842, 'eval_steps_per_second': 147.648, 'epoch': 15.0}
(5165, 96, 6)

 43%|████▎     | 60/138 [16:31<22:58, 17.67s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5479_MIT-Daudpur_Kothi_Muzaffarpur_BSPCB_15Min_metrics.json

============================================================
Processing: site_5604_Kokapet_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.258862473747947 seconds, Total Train Time = 8.952963829040527
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.69603431224823, 'eval_runtime': 0.5243, 'eval_samples_per_second': 9851.82, 'eval_steps_per_second': 154.501, 'epoch': 11.0}
(5165, 96, 6)

 44%|████▍     | 61/138 [16:46<21:40, 16.89s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5604_Kokapet_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_5363_Perungudi_Chennai_TNPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2500014781951904 seconds, Total Train Time = 14.335764169692993
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 2.1128358840942383, 'eval_runtime': 0.5472, 'eval_samples_per_second': 9439.09, 'eval_steps_per_second': 148.028, 'epoch': 15.0}
(5165, 96, 6)

 45%|████▍     | 62/138 [17:06<22:40, 17.91s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5363_Perungudi_Chennai_TNPCB_15Min_metrics.json

============================================================
Processing: site_5653_Siltara_Phase-II_Raipur_CECB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00035938136638046257

OPTIMAL SUGGESTED LEARNING RATE = 0.00035938136638046257
Using learning rate = 0.00035938136638046257

[TrackingCallback] Mean Epoch Time = 0.24680289355191318 seconds, Total Train Time = 8.71138048171997
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.2691456079483032, 'eval_runtime': 0.539, 'eval_samples_per_second': 9583.14, 'eval_steps_per_second': 150.287, 'epoch': 11.0}
(5165, 96, 6)

 46%|████▌     | 63/138 [17:21<21:13, 16.98s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5653_Siltara_Phase-II_Raipur_CECB_15Min_metrics.json

============================================================
Processing: site_5552_DM_Office_Kasipur_Samastipur_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2572462757428487 seconds, Total Train Time = 9.75025486946106
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.20215827226638794, 'eval_runtime': 0.5168, 'eval_samples_per_second': 9994.93, 'eval_steps_per_second': 156.745, 'epoch': 12.0}
(5165, 96, 6)

 46%|████▋     | 64/138 [17:39<21:17, 17.26s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5552_DM_Office_Kasipur_Samastipur_BSPCB_15Min_metrics.json

============================================================
Processing: site_303_Opp_GPO_Civil_Lines_Nagpur_MPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2702054110440341 seconds, Total Train Time = 9.52952527999878
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.2772562503814697, 'eval_runtime': 0.6208, 'eval_samples_per_second': 8320.373, 'eval_steps_per_second': 130.484, 'epoch': 11.0}
(5165, 96, 6)

 47%|████▋     | 65/138 [17:55<20:35, 16.92s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_303_Opp_GPO_Civil_Lines_Nagpur_MPCB_15Min_metrics.json

============================================================
Processing: site_5660_32Bungalows_Bhilai_CECB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2632734775543213 seconds, Total Train Time = 9.20358157157898
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.600355863571167, 'eval_runtime': 0.5434, 'eval_samples_per_second': 9504.126, 'eval_steps_per_second': 149.048, 'epoch': 11.0}
(5165, 96, 6)

 48%|████▊     | 66/138 [18:13<20:36, 17.17s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5660_32Bungalows_Bhilai_CECB_15Min_metrics.json

============================================================
Processing: site_1542_Yamunapuram_Bulandshahr_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.26510327202933176 seconds, Total Train Time = 11.43755054473877
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5484733581542969, 'eval_runtime': 0.5267, 'eval_samples_per_second': 9806.718, 'eval_steps_per_second': 153.794, 'epoch': 14.0}
(5165, 96, 6)

 49%|████▊     | 67/138 [18:30<20:26, 17.27s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1542_Yamunapuram_Bulandshahr_UPPCB_15Min_metrics.json

============================================================
Processing: site_1391_RIICO_Ind._Area_III_Bhiwadi_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00035938136638046257

OPTIMAL SUGGESTED LEARNING RATE = 0.00035938136638046257
Using learning rate = 0.00035938136638046257

[TrackingCallback] Mean Epoch Time = 0.2610045779835094 seconds, Total Train Time = 8.985182285308838
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.39530646800994873, 'eval_runtime': 0.5222, 'eval_samples_per_second': 9890.095, 'eval_steps_per_second': 155.101, 'epoch': 11.0}
(5165, 96, 6)

 49%|████▉     | 68/138 [18:48<20:06, 17.24s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1391_RIICO_Ind._Area_III_Bhiwadi_RSPCB_15Min_metrics.json

============================================================
Processing: site_5464_Manoharpur_Agra_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.25763094425201416 seconds, Total Train Time = 9.675373792648315
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.271450400352478, 'eval_runtime': 0.5289, 'eval_samples_per_second': 9765.196, 'eval_steps_per_second': 153.142, 'epoch': 12.0}
(5165, 96, 6)

 50%|█████     | 69/138 [19:03<19:17, 16.78s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5464_Manoharpur_Agra_UPPCB_15Min_metrics.json

============================================================
Processing: site_5081_Sanjay_Nagar_Ghaziabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2650366046211936 seconds, Total Train Time = 9.222724676132202
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4495226740837097, 'eval_runtime': 0.6185, 'eval_samples_per_second': 8351.036, 'eval_steps_per_second': 130.965, 'epoch': 11.0}
(5165, 96, 6)

 51%|█████     | 70/138 [19:21<19:21, 17.08s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5081_Sanjay_Nagar_Ghaziabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_1425_Major_Dhyan_Chand_National_Stadium_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2564938718622381 seconds, Total Train Time = 8.953129529953003
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5552458167076111, 'eval_runtime': 0.5561, 'eval_samples_per_second': 9288.087, 'eval_steps_per_second': 145.66, 'epoch': 11.0}
(5165, 96, 6)

 51%|█████▏    | 71/138 [19:36<18:21, 16.44s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1425_Major_Dhyan_Chand_National_Stadium_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_262_Central_University_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.2807719490744851 seconds, Total Train Time = 9.599349737167358
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 2.7750673294067383, 'eval_runtime': 0.5703, 'eval_samples_per_second': 9056.556, 'eval_steps_per_second': 142.029, 'epoch': 11.0}
(5165, 96, 6)

 52%|█████▏    | 72/138 [19:52<17:51, 16.23s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_262_Central_University_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_5554_Buddhi_Vihar_Moradabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.26253045522249663 seconds, Total Train Time = 10.711075067520142
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5720462203025818, 'eval_runtime': 0.5139, 'eval_samples_per_second': 10051.138, 'eval_steps_per_second': 157.627, 'epoch': 13.0}
(5165, 96, 6)

 53%|█████▎    | 73/138 [20:11<18:42, 17.27s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5554_Buddhi_Vihar_Moradabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_1450_Kalal_Majra_Khanna_PPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.25765360485423694 seconds, Total Train Time = 8.953967332839966
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5941269397735596, 'eval_runtime': 0.5316, 'eval_samples_per_second': 9716.658, 'eval_steps_per_second': 152.381, 'epoch': 11.0}
(5165, 96, 6)

 54%|█████▎    | 74/138 [20:26<17:39, 16.56s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1450_Kalal_Majra_Khanna_PPCB_15Min_metrics.json

============================================================
Processing: site_115_NSIT_Dwarka_Delhi_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.25362101468172943 seconds, Total Train Time = 8.861425161361694
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.8902947902679443, 'eval_runtime': 0.5407, 'eval_samples_per_second': 9552.942, 'eval_steps_per_second': 149.814, 'epoch': 11.0}
(5165, 96, 6)

 54%|█████▍    | 75/138 [20:41<16:48, 16.01s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_115_NSIT_Dwarka_Delhi_CPCB_15Min_metrics.json

============================================================
Processing: site_5263_Samanpura_Patna_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.25815918228842993 seconds, Total Train Time = 8.807249307632446
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.22989170253276825, 'eval_runtime': 0.5555, 'eval_samples_per_second': 9297.123, 'eval_steps_per_second': 145.802, 'epoch': 11.0}
(5165, 96, 6)

 55%|█████▌    | 76/138 [20:58<16:48, 16.27s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5263_Samanpura_Patna_BSPCB_15Min_metrics.json

============================================================
Processing: site_1390_Moti_Doongri_Alwar_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2590826153755188 seconds, Total Train Time = 9.720757484436035
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5521877408027649, 'eval_runtime': 0.5317, 'eval_samples_per_second': 9714.283, 'eval_steps_per_second': 152.344, 'epoch': 12.0}
(5165, 96, 6)

 56%|█████▌    | 77/138 [21:14<16:20, 16.08s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1390_Moti_Doongri_Alwar_RSPCB_15Min_metrics.json

============================================================
Processing: site_5582_Sector-53_Chandigarh_CPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.25398356264287775 seconds, Total Train Time = 10.909734964370728
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.34094494581222534, 'eval_runtime': 0.5764, 'eval_samples_per_second': 8960.679, 'eval_steps_per_second': 140.526, 'epoch': 11.0}
(5165, 96, 6)

 57%|█████▋    | 78/138 [21:30<16:19, 16.33s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5582_Sector-53_Chandigarh_CPCC_15Min_metrics.json

============================================================
Processing: site_5587_Bardowali_Agartala_Tripura_SPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00035938136638046257

OPTIMAL SUGGESTED LEARNING RATE = 0.00035938136638046257
Using learning rate = 0.00035938136638046257

[TrackingCallback] Mean Epoch Time = 0.2525236823342063 seconds, Total Train Time = 8.82460355758667
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.17262791097164154, 'eval_runtime': 0.522, 'eval_samples_per_second': 9895.457, 'eval_steps_per_second': 155.185, 'epoch': 11.0}
(5165, 96, 6)

 57%|█████▋    | 79/138 [21:45<15:38, 15.91s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5587_Bardowali_Agartala_Tripura_SPCB_15Min_metrics.json

============================================================
Processing: site_5337_Industrial_Area_Hajipur_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.001917910261672489

OPTIMAL SUGGESTED LEARNING RATE = 0.001917910261672489
Using learning rate = 0.001917910261672489

[TrackingCallback] Mean Epoch Time = 0.2584008520299738 seconds, Total Train Time = 10.995466232299805
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5097326040267944, 'eval_runtime': 0.5074, 'eval_samples_per_second': 10178.738, 'eval_steps_per_second': 159.628, 'epoch': 11.0}
(5165, 96, 6)

 58%|█████▊    | 80/138 [22:02<15:37, 16.17s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5337_Industrial_Area_Hajipur_BSPCB_15Min_metrics.json

============================================================
Processing: site_5662_Civil_Lines_Sagar_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.001917910261672489

OPTIMAL SUGGESTED LEARNING RATE = 0.001917910261672489
Using learning rate = 0.001917910261672489

[TrackingCallback] Mean Epoch Time = 0.2518110925501043 seconds, Total Train Time = 8.801732301712036
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.9829696416854858, 'eval_runtime': 0.5305, 'eval_samples_per_second': 9735.487, 'eval_steps_per_second': 152.677, 'epoch': 11.0}
(5165, 96, 6)

 59%|█████▊    | 81/138 [22:17<14:58, 15.77s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5662_Civil_Lines_Sagar_MPPCB_15Min_metrics.json

============================================================
Processing: site_5669_Central_Academy_for_SFS_Byrnihat_PCBA_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.25292847373268823 seconds, Total Train Time = 10.850027084350586
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.05457330122590065, 'eval_runtime': 0.5297, 'eval_samples_per_second': 9751.32, 'eval_steps_per_second': 152.925, 'epoch': 11.0}
(5165, 96, 6)

 59%|█████▉    | 82/138 [22:34<15:04, 16.15s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5669_Central_Academy_for_SFS_Byrnihat_PCBA_15Min_metrics.json

============================================================
Processing: site_297_Talkatora_District_Industries_Center_Lucknow_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2508575049313632 seconds, Total Train Time = 8.524890661239624
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.29690808057785034, 'eval_runtime': 0.5432, 'eval_samples_per_second': 9508.823, 'eval_steps_per_second': 149.122, 'epoch': 11.0}
(5165, 96, 6)

 60%|██████    | 83/138 [22:49<14:21, 15.66s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_297_Talkatora_District_Industries_Center_Lucknow_CPCB_15Min_metrics.json

============================================================
Processing: site_5482_Rohta_Agra_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.24692427028309216 seconds, Total Train Time = 8.66602349281311
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.9328482151031494, 'eval_runtime': 2.7161, 'eval_samples_per_second': 1901.614, 'eval_steps_per_second': 29.822, 'epoch': 11.0}
(5165, 96, 6)

 61%|██████    | 84/138 [23:05<14:23, 15.99s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5482_Rohta_Agra_UPPCB_15Min_metrics.json

============================================================
Processing: site_134_Police_Commissionerate_Jaipur_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.25012272054498846 seconds, Total Train Time = 8.62967324256897
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5428065061569214, 'eval_runtime': 0.533, 'eval_samples_per_second': 9690.497, 'eval_steps_per_second': 151.971, 'epoch': 11.0}
(5165, 96, 6)

 62%|██████▏   | 85/138 [23:20<13:47, 15.60s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_134_Police_Commissionerate_Jaipur_RSPCB_15Min_metrics.json

============================================================
Processing: site_5680_Lingaraj_Nagar_Hubballi_KSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.25728583335876465 seconds, Total Train Time = 8.949333190917969
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.052456945180892944, 'eval_runtime': 0.5516, 'eval_samples_per_second': 9364.423, 'eval_steps_per_second': 146.857, 'epoch': 11.0}
(5165, 96, 6)

 62%|██████▏   | 86/138 [23:35<13:18, 15.35s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5680_Lingaraj_Nagar_Hubballi_KSPCB_15Min_metrics.json

============================================================
Processing: site_5600_Nacharam_TSIIC_IALA_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2522773912974766 seconds, Total Train Time = 11.214742660522461
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.37160927057266235, 'eval_runtime': 0.6408, 'eval_samples_per_second': 8060.069, 'eval_steps_per_second': 126.402, 'epoch': 14.0}
(5165, 96, 6)

 63%|██████▎   | 87/138 [23:55<14:17, 16.81s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5600_Nacharam_TSIIC_IALA_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_301_Anand_Vihar_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2564269946171687 seconds, Total Train Time = 10.321634531021118
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6645953059196472, 'eval_runtime': 0.5756, 'eval_samples_per_second': 8972.964, 'eval_steps_per_second': 140.718, 'epoch': 13.0}
(5165, 96, 6)

 64%|██████▍   | 88/138 [24:11<13:51, 16.63s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_301_Anand_Vihar_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5599_Kompally_Municipal_Office_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.37946240107218426 seconds, Total Train Time = 13.677483081817627
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.3127895593643188, 'eval_runtime': 0.5702, 'eval_samples_per_second': 9058.661, 'eval_steps_per_second': 142.062, 'epoch': 15.0}
(5165, 96, 6)

 64%|██████▍   | 89/138 [24:31<14:18, 17.51s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5599_Kompally_Municipal_Office_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_113_Shadipur_Delhi_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.25335723703557794 seconds, Total Train Time = 8.656651020050049
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6207885146141052, 'eval_runtime': 0.4896, 'eval_samples_per_second': 10549.09, 'eval_steps_per_second': 165.436, 'epoch': 11.0}
(5165, 96, 6)

 65%|██████▌   | 90/138 [24:46<13:20, 16.68s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_113_Shadipur_Delhi_CPCB_15Min_metrics.json

============================================================
Processing: site_304_Gangapur_Road_Nashik_MPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.001917910261672489

OPTIMAL SUGGESTED LEARNING RATE = 0.001917910261672489
Using learning rate = 0.001917910261672489

[TrackingCallback] Mean Epoch Time = 0.26119568131186743 seconds, Total Train Time = 8.930684089660645
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4966403543949127, 'eval_runtime': 0.5585, 'eval_samples_per_second': 9247.969, 'eval_steps_per_second': 145.031, 'epoch': 11.0}
(5165, 96, 6)

 66%|██████▌   | 91/138 [25:03<13:09, 16.80s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_304_Gangapur_Road_Nashik_MPCB_15Min_metrics.json

============================================================
Processing: site_1430_Rohini_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2464059049432928 seconds, Total Train Time = 8.60929250717163
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.464322566986084, 'eval_runtime': 0.532, 'eval_samples_per_second': 9709.298, 'eval_steps_per_second': 152.266, 'epoch': 11.0}
(5165, 96, 6)

 67%|██████▋   | 92/138 [25:17<12:18, 16.06s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1430_Rohini_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5551_Police_Line_Saharsa_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.2412925362586975 seconds, Total Train Time = 9.241133451461792
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3370573818683624, 'eval_runtime': 0.5378, 'eval_samples_per_second': 9603.345, 'eval_steps_per_second': 150.604, 'epoch': 12.0}
(5165, 96, 6)

 67%|██████▋   | 93/138 [25:32<11:50, 15.78s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5551_Police_Line_Saharsa_BSPCB_15Min_metrics.json

============================================================
Processing: site_5548_Kareemganj_Gaya_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0002477076355991711

OPTIMAL SUGGESTED LEARNING RATE = 0.0002477076355991711
Using learning rate = 0.0002477076355991711

[TrackingCallback] Mean Epoch Time = 0.24873769283294678 seconds, Total Train Time = 14.15915060043335
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.24721862375736237, 'eval_runtime': 0.578, 'eval_samples_per_second': 8936.7, 'eval_steps_per_second': 140.15, 'epoch': 18.0}
(5165, 96, 6)

 68%|██████▊   | 94/138 [25:54<13:00, 17.74s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5548_Kareemganj_Gaya_BSPCB_15Min_metrics.json

============================================================
Processing: site_144_Vasundhara_Ghaziabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.2557437853379683 seconds, Total Train Time = 8.962226629257202
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6180709600448608, 'eval_runtime': 0.4987, 'eval_samples_per_second': 10356.044, 'eval_steps_per_second': 162.408, 'epoch': 11.0}
(5165, 96, 6)

 69%|██████▉   | 95/138 [26:11<12:32, 17.51s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_144_Vasundhara_Ghaziabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_1426_Narela_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.24732906168157404 seconds, Total Train Time = 8.597639083862305
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5014715790748596, 'eval_runtime': 0.5319, 'eval_samples_per_second': 9711.27, 'eval_steps_per_second': 152.297, 'epoch': 11.0}
(5165, 96, 6)

 70%|██████▉   | 96/138 [26:27<11:47, 16.84s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1426_Narela_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_1418_Asansol_Court_Area_Asansol_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.2558390660719438 seconds, Total Train Time = 8.861865043640137
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.33242395520210266, 'eval_runtime': 0.5216, 'eval_samples_per_second': 9901.35, 'eval_steps_per_second': 155.278, 'epoch': 11.0}
(5165, 96, 6)

 70%|███████   | 97/138 [26:44<11:33, 16.90s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1418_Asansol_Court_Area_Asansol_WBPCB_15Min_metrics.json

============================================================
Processing: site_5066_Sector-10_Gandhinagar_GPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.2572971907528964 seconds, Total Train Time = 8.899787664413452
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.48256736993789673, 'eval_runtime': 0.5199, 'eval_samples_per_second': 9934.884, 'eval_steps_per_second': 155.804, 'epoch': 11.0}
(5165, 96, 6)

 71%|███████   | 98/138 [26:58<10:48, 16.22s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5066_Sector-10_Gandhinagar_GPCB_15Min_metrics.json

============================================================
Processing: site_5083_Loni_Ghaziabad_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.2501345547762784 seconds, Total Train Time = 8.552151679992676
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6547555923461914, 'eval_runtime': 0.5207, 'eval_samples_per_second': 9918.572, 'eval_steps_per_second': 155.548, 'epoch': 11.0}
(5165, 96, 6)

 72%|███████▏  | 99/138 [27:13<10:13, 15.73s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5083_Loni_Ghaziabad_UPPCB_15Min_metrics.json

============================================================
Processing: site_1421_Dr._Karni_Singh_Shooting_Range_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.25534740361300384 seconds, Total Train Time = 10.92151403427124
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3423416018486023, 'eval_runtime': 0.5105, 'eval_samples_per_second': 10117.797, 'eval_steps_per_second': 158.672, 'epoch': 11.0}
(5165, 96, 6)

 72%|███████▏  | 100/138 [27:30<10:11, 16.08s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1421_Dr._Karni_Singh_Shooting_Range_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5111_Jadavpur_Kolkata_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.24760401248931885 seconds, Total Train Time = 9.29245924949646
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.8632519245147705, 'eval_runtime': 0.5202, 'eval_samples_per_second': 9928.118, 'eval_steps_per_second': 155.697, 'epoch': 12.0}
(5165, 96, 6)

 73%|███████▎  | 101/138 [27:45<09:45, 15.83s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5111_Jadavpur_Kolkata_WBPCB_15Min_metrics.json

============================================================
Processing: site_256_Golden_Temple_Amritsar_PPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.4459983002055775 seconds, Total Train Time = 10.827640533447266
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.3720799684524536, 'eval_runtime': 0.5273, 'eval_samples_per_second': 9796.005, 'eval_steps_per_second': 153.626, 'epoch': 11.0}
(5165, 96, 6)

 74%|███████▍  | 102/138 [28:02<09:45, 16.26s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_256_Golden_Temple_Amritsar_PPCB_15Min_metrics.json

============================================================
Processing: site_5539_Kharahiya_Basti_Araria_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.25531796975569293 seconds, Total Train Time = 8.783875465393066
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.0110180377960205, 'eval_runtime': 0.5238, 'eval_samples_per_second': 9860.034, 'eval_steps_per_second': 154.63, 'epoch': 11.0}
(5165, 96, 6)

 75%|███████▍  | 103/138 [28:17<09:12, 15.79s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5539_Kharahiya_Basti_Araria_BSPCB_15Min_metrics.json

============================================================
Processing: site_5652_AIIMS_Raipur_CECB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.25312688133933325 seconds, Total Train Time = 10.947859525680542
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.22362034022808075, 'eval_runtime': 0.5193, 'eval_samples_per_second': 9945.83, 'eval_steps_per_second': 155.975, 'epoch': 11.0}
(5165, 96, 6)

 75%|███████▌  | 104/138 [28:34<09:07, 16.10s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5652_AIIMS_Raipur_CECB_15Min_metrics.json

============================================================
Processing: site_125_Punjabi_Bagh_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.2584995789961381 seconds, Total Train Time = 8.790382146835327
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6007503271102905, 'eval_runtime': 0.5528, 'eval_samples_per_second': 9342.756, 'eval_steps_per_second': 146.518, 'epoch': 11.0}
(5165, 96, 6)

 76%|███████▌  | 105/138 [28:49<08:38, 15.71s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_125_Punjabi_Bagh_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_1392_Civil_Lines__Ajmer_RSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.45290637016296387 seconds, Total Train Time = 11.042402982711792
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.7851810455322266, 'eval_runtime': 0.5039, 'eval_samples_per_second': 10250.795, 'eval_steps_per_second': 160.758, 'epoch': 11.0}
(5165, 96, 6)

 77%|███████▋  | 106/138 [29:06<08:34, 16.09s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1392_Civil_Lines__Ajmer_RSPCB_15Min_metrics.json

============================================================
Processing: site_5247_T_T_Nagar_Bhopal_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0002477076355991711

OPTIMAL SUGGESTED LEARNING RATE = 0.0002477076355991711
Using learning rate = 0.0002477076355991711

[TrackingCallback] Mean Epoch Time = 0.2610502459786155 seconds, Total Train Time = 9.031260251998901
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6437728404998779, 'eval_runtime': 0.5598, 'eval_samples_per_second': 9226.008, 'eval_steps_per_second': 144.687, 'epoch': 11.0}
(5165, 96, 6)

 78%|███████▊  | 107/138 [29:21<08:10, 15.83s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5247_T_T_Nagar_Bhopal_MPPCB_15Min_metrics.json

============================================================
Processing: site_5475_Maldahiya_Varanasi_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.24764102697372437 seconds, Total Train Time = 9.402180671691895
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.22865067422389984, 'eval_runtime': 0.526, 'eval_samples_per_second': 9818.461, 'eval_steps_per_second': 153.978, 'epoch': 12.0}
(5165, 96, 6)

 78%|███████▊  | 108/138 [29:38<08:07, 16.27s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5475_Maldahiya_Varanasi_UPPCB_15Min_metrics.json

============================================================
Processing: site_5585_Sardar_Patel_Inter_College_Baghpat_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0010974987654930567

OPTIMAL SUGGESTED LEARNING RATE = 0.0010974987654930567
Using learning rate = 0.0010974987654930567

[TrackingCallback] Mean Epoch Time = 0.26712439276955346 seconds, Total Train Time = 9.247057437896729
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4334968626499176, 'eval_runtime': 0.5085, 'eval_samples_per_second': 10157.195, 'eval_steps_per_second': 159.29, 'epoch': 11.0}
(5165, 96, 6)

 79%|███████▉  | 109/138 [29:53<07:43, 15.97s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5585_Sardar_Patel_Inter_College_Baghpat_UPPCB_15Min_metrics.json

============================================================
Processing: site_5632_Gulzarpet_Anantapur_APPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.25595281340859155 seconds, Total Train Time = 8.841290712356567
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5087425708770752, 'eval_runtime': 0.5159, 'eval_samples_per_second': 10011.142, 'eval_steps_per_second': 157.0, 'epoch': 11.0}
(5165, 96, 6)

 80%|███████▉  | 110/138 [30:10<07:34, 16.23s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5632_Gulzarpet_Anantapur_APPCB_15Min_metrics.json

============================================================
Processing: site_5338_SFTI_Kusdihra_Gaya_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.25237900560552423 seconds, Total Train Time = 8.664689540863037
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.12061873823404312, 'eval_runtime': 0.5093, 'eval_samples_per_second': 10140.791, 'eval_steps_per_second': 159.033, 'epoch': 11.0}
(5165, 96, 6)

 80%|████████  | 111/138 [30:25<07:04, 15.72s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5338_SFTI_Kusdihra_Gaya_BSPCB_15Min_metrics.json

============================================================
Processing: site_5126_Rabindra_Sarobar_Kolkata_WBPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.25419382615522906 seconds, Total Train Time = 8.732234239578247
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5553626418113708, 'eval_runtime': 0.5292, 'eval_samples_per_second': 9759.789, 'eval_steps_per_second': 153.058, 'epoch': 11.0}
(5165, 96, 6)

 81%|████████  | 112/138 [30:40<06:41, 15.44s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5126_Rabindra_Sarobar_Kolkata_WBPCB_15Min_metrics.json

============================================================
Processing: site_5658_Girls_College_Sivasagar_PCBA_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000298364724028334

OPTIMAL SUGGESTED LEARNING RATE = 0.000298364724028334
Using learning rate = 0.000298364724028334

[TrackingCallback] Mean Epoch Time = 0.25660436803644354 seconds, Total Train Time = 11.018567323684692
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6654837131500244, 'eval_runtime': 0.5214, 'eval_samples_per_second': 9906.245, 'eval_steps_per_second': 155.354, 'epoch': 11.0}
(5165, 96, 6)

 82%|████████▏ | 113/138 [30:56<06:35, 15.83s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5658_Girls_College_Sivasagar_PCBA_15Min_metrics.json

============================================================
Processing: site_1437_Model_Town_Patiala_PPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.2405892718922008 seconds, Total Train Time = 8.372830867767334
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.42701002955436707, 'eval_runtime': 0.5213, 'eval_samples_per_second': 9907.259, 'eval_steps_per_second': 155.37, 'epoch': 11.0}
(5165, 96, 6)

 83%|████████▎ | 114/138 [31:10<06:07, 15.32s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1437_Model_Town_Patiala_PPCB_15Min_metrics.json

============================================================
Processing: site_271_Chauhan_Colony_Chandrapur_MPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.4457218213514848 seconds, Total Train Time = 10.879712343215942
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.42079731822013855, 'eval_runtime': 0.5084, 'eval_samples_per_second': 10158.328, 'eval_steps_per_second': 159.308, 'epoch': 11.0}
(5165, 96, 6)

 83%|████████▎ | 115/138 [31:27<06:01, 15.72s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_271_Chauhan_Colony_Chandrapur_MPCB_15Min_metrics.json

============================================================
Processing: site_1562_Sri_Aurobindo_Marg_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.2590036988258362 seconds, Total Train Time = 9.750560522079468
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3231469392776489, 'eval_runtime': 0.4938, 'eval_samples_per_second': 10459.899, 'eval_steps_per_second': 164.037, 'epoch': 12.0}
(5165, 96, 6)

 84%|████████▍ | 116/138 [31:43<05:44, 15.66s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1562_Sri_Aurobindo_Marg_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5659_Hathkhoj_Bhilai_CECB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.2448346181349321 seconds, Total Train Time = 10.845610618591309
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.2808210551738739, 'eval_runtime': 0.5318, 'eval_samples_per_second': 9712.977, 'eval_steps_per_second': 152.324, 'epoch': 11.0}
(5165, 96, 6)

 85%|████████▍ | 117/138 [31:59<05:36, 16.00s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5659_Hathkhoj_Bhilai_CECB_15Min_metrics.json

============================================================
Processing: site_199_Bollaram_Industrial_Area_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0015922827933410938

OPTIMAL SUGGESTED LEARNING RATE = 0.0015922827933410938
Using learning rate = 0.0015922827933410938

[TrackingCallback] Mean Epoch Time = 0.2367896166714755 seconds, Total Train Time = 8.216470956802368
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3372907042503357, 'eval_runtime': 0.4999, 'eval_samples_per_second': 10332.784, 'eval_steps_per_second': 162.044, 'epoch': 11.0}
(5165, 96, 6)

 86%|████████▌ | 118/138 [32:13<05:08, 15.41s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_199_Bollaram_Industrial_Area_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_5124_Urban_Chamarajanagar_KSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.408282470703125 seconds, Total Train Time = 14.306256771087646
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.676342785358429, 'eval_runtime': 0.5768, 'eval_samples_per_second': 8955.06, 'eval_steps_per_second': 140.438, 'epoch': 15.0}
(5165, 96, 6)

 86%|████████▌ | 119/138 [32:34<05:20, 16.88s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5124_Urban_Chamarajanagar_KSPCB_15Min_metrics.json

============================================================
Processing: site_252_Plammoodu_Thiruvananthapuram_Kerala_PCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.001917910261672489

OPTIMAL SUGGESTED LEARNING RATE = 0.001917910261672489
Using learning rate = 0.001917910261672489

[TrackingCallback] Mean Epoch Time = 0.2284236171028831 seconds, Total Train Time = 7.980316400527954
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.988155722618103, 'eval_runtime': 0.5016, 'eval_samples_per_second': 10297.206, 'eval_steps_per_second': 161.486, 'epoch': 11.0}
(5165, 96, 6)

 87%|████████▋ | 120/138 [32:47<04:46, 15.93s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_252_Plammoodu_Thiruvananthapuram_Kerala_PCB_15Min_metrics.json

============================================================
Processing: site_5248_Chhoti_Gwaltoli_Indore_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.24289573322642932 seconds, Total Train Time = 8.479177713394165
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.49409785866737366, 'eval_runtime': 0.521, 'eval_samples_per_second': 9913.634, 'eval_steps_per_second': 155.47, 'epoch': 11.0}
(5165, 96, 6)

 88%|████████▊ | 121/138 [33:04<04:33, 16.08s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5248_Chhoti_Gwaltoli_Indore_MPPCB_15Min_metrics.json

============================================================
Processing: site_272_Kendriya_Vidyalaya_Lucknow_CPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0027825594022071257

OPTIMAL SUGGESTED LEARNING RATE = 0.0027825594022071257
Using learning rate = 0.0027825594022071257

[TrackingCallback] Mean Epoch Time = 0.24586855281483044 seconds, Total Train Time = 8.389391422271729
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.7602307200431824, 'eval_runtime': 0.5001, 'eval_samples_per_second': 10327.72, 'eval_steps_per_second': 161.964, 'epoch': 11.0}
(5165, 96, 6)

 88%|████████▊ | 122/138 [33:18<04:08, 15.53s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_272_Kendriya_Vidyalaya_Lucknow_CPCB_15Min_metrics.json

============================================================
Processing: site_5273_City_Center_Gwalior_MPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.23312436450611462 seconds, Total Train Time = 8.195964574813843
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.3730279803276062, 'eval_runtime': 0.5766, 'eval_samples_per_second': 8957.841, 'eval_steps_per_second': 140.481, 'epoch': 11.0}
(5165, 96, 6)

 89%|████████▉ | 123/138 [33:32<03:46, 15.13s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5273_City_Center_Gwalior_MPPCB_15Min_metrics.json

============================================================
Processing: site_5483_Omex_Eternity_Vrindavan_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.4025004059076309 seconds, Total Train Time = 15.019217014312744
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.21477116644382477, 'eval_runtime': 0.5012, 'eval_samples_per_second': 10305.959, 'eval_steps_per_second': 161.623, 'epoch': 16.0}
(5165, 96, 6)

 90%|████████▉ | 124/138 [33:53<03:55, 16.81s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5483_Omex_Eternity_Vrindavan_UPPCB_15Min_metrics.json

============================================================
Processing: site_5336_DRM_Office_Danapur_Patna_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.23711931705474854 seconds, Total Train Time = 9.02886700630188
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.2999884784221649, 'eval_runtime': 0.5199, 'eval_samples_per_second': 9934.761, 'eval_steps_per_second': 155.802, 'epoch': 12.0}
(5165, 96, 6)

 91%|█████████ | 125/138 [34:08<03:31, 16.23s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5336_DRM_Office_Danapur_Patna_BSPCB_15Min_metrics.json

============================================================
Processing: site_1432_Sonia_Vihar_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.24839979952031915 seconds, Total Train Time = 8.637366533279419
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.7227736115455627, 'eval_runtime': 0.5955, 'eval_samples_per_second': 8672.78, 'eval_steps_per_second': 136.011, 'epoch': 11.0}
(5165, 96, 6)

 91%|█████████▏| 126/138 [34:25<03:16, 16.35s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1432_Sonia_Vihar_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5598_Somajiguda_Hyderabad_TSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0013219411484660286

OPTIMAL SUGGESTED LEARNING RATE = 0.0013219411484660286
Using learning rate = 0.0013219411484660286

[TrackingCallback] Mean Epoch Time = 0.23657974329861728 seconds, Total Train Time = 8.168689012527466
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.651198387145996, 'eval_runtime': 0.5114, 'eval_samples_per_second': 10099.171, 'eval_steps_per_second': 158.38, 'epoch': 11.0}
(5165, 96, 6)

 92%|█████████▏| 127/138 [34:39<02:52, 15.65s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5598_Somajiguda_Hyderabad_TSPCB_15Min_metrics.json

============================================================
Processing: site_5461_Jhunsi_Prayagraj_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.2673179669813676 seconds, Total Train Time = 11.617236852645874
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.185500979423523, 'eval_runtime': 0.5891, 'eval_samples_per_second': 8768.327, 'eval_steps_per_second': 137.509, 'epoch': 11.0}
(5165, 96, 6)

 93%|█████████▎| 128/138 [34:56<02:42, 16.21s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5461_Jhunsi_Prayagraj_UPPCB_15Min_metrics.json

============================================================
Processing: site_1427_Najafgarh_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.23567461967468262 seconds, Total Train Time = 8.917365074157715
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.5974011421203613, 'eval_runtime': 0.4741, 'eval_samples_per_second': 10893.732, 'eval_steps_per_second': 170.841, 'epoch': 12.0}
(5165, 96, 6)

 93%|█████████▎| 129/138 [35:11<02:22, 15.79s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1427_Najafgarh_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_5668_Bata_Chowk_Nalbari_PCBA_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.25287196852944116 seconds, Total Train Time = 10.89386510848999
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.21343713998794556, 'eval_runtime': 0.518, 'eval_samples_per_second': 9971.894, 'eval_steps_per_second': 156.384, 'epoch': 11.0}
(5165, 96, 6)

 94%|█████████▍| 130/138 [35:28<02:08, 16.06s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5668_Bata_Chowk_Nalbari_PCBA_15Min_metrics.json

============================================================
Processing: site_5549_Mariam_Nagar_Purnia_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.23712809880574545 seconds, Total Train Time = 8.91532039642334
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.3303781747817993, 'eval_runtime': 0.522, 'eval_samples_per_second': 9894.404, 'eval_steps_per_second': 155.169, 'epoch': 12.0}
(5165, 96, 6)

 95%|█████████▍| 131/138 [35:42<01:48, 15.55s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5549_Mariam_Nagar_Purnia_BSPCB_15Min_metrics.json

============================================================
Processing: site_5465_Sector-3B_Avas_Vikas_Colony_Agra_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.00043287612810830566

OPTIMAL SUGGESTED LEARNING RATE = 0.00043287612810830566
Using learning rate = 0.00043287612810830566

[TrackingCallback] Mean Epoch Time = 0.24686980247497559 seconds, Total Train Time = 11.098541736602783
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 1.0519096851348877, 'eval_runtime': 0.527, 'eval_samples_per_second': 9800.742, 'eval_steps_per_second': 153.7, 'epoch': 11.0}
(5165, 96, 6)

 96%|█████████▌| 132/138 [35:59<01:36, 16.02s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5465_Sector-3B_Avas_Vikas_Colony_Agra_UPPCB_15Min_metrics.json

============================================================
Processing: site_5462_Kukrail_Picnic_Spot-1_Lucknow_UPPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.23968022519891913 seconds, Total Train Time = 8.276986122131348
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4961371421813965, 'eval_runtime': 0.4877, 'eval_samples_per_second': 10590.45, 'eval_steps_per_second': 166.084, 'epoch': 11.0}
(5165, 96, 6)

 96%|█████████▋| 133/138 [36:13<01:17, 15.42s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5462_Kukrail_Picnic_Spot-1_Lucknow_UPPCB_15Min_metrics.json

============================================================
Processing: site_5547_SDM_Office_Khagra_Kishanganj_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0005214008287999684

OPTIMAL SUGGESTED LEARNING RATE = 0.0005214008287999684
Using learning rate = 0.0005214008287999684

[TrackingCallback] Mean Epoch Time = 0.24368036877025256 seconds, Total Train Time = 8.641150951385498
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.30641135573387146, 'eval_runtime': 0.5216, 'eval_samples_per_second': 9901.341, 'eval_steps_per_second': 155.278, 'epoch': 11.0}
(5165, 96, 6)

 97%|█████████▋| 134/138 [36:30<01:03, 15.81s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5547_SDM_Office_Khagra_Kishanganj_BSPCB_15Min_metrics.json

============================================================
Processing: site_1435_Vivek_Vihar_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0009111627561154895

OPTIMAL SUGGESTED LEARNING RATE = 0.0009111627561154895
Using learning rate = 0.0009111627561154895

[TrackingCallback] Mean Epoch Time = 0.25044471567327325 seconds, Total Train Time = 8.693315982818604
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.5541200637817383, 'eval_runtime': 0.5004, 'eval_samples_per_second': 10322.159, 'eval_steps_per_second': 161.877, 'epoch': 11.0}
(5165, 96, 6)

 98%|█████████▊| 135/138 [36:44<00:46, 15.36s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1435_Vivek_Vihar_Delhi_DPCC_15Min_metrics.json

============================================================
Processing: site_1555_Hombegowda_Nagar_Bengaluru_KSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.23655826395208185 seconds, Total Train Time = 8.228120803833008
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.4658125638961792, 'eval_runtime': 0.5599, 'eval_samples_per_second': 9224.386, 'eval_steps_per_second': 144.661, 'epoch': 11.0}
(5165, 96, 6)

 99%|█████████▊| 136/138 [36:58<00:30, 15.01s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_1555_Hombegowda_Nagar_Bengaluru_KSPCB_15Min_metrics.json

============================================================
Processing: site_5541_Mayaganj_Bhagalpur_BSPCB_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.0006280291441834253

OPTIMAL SUGGESTED LEARNING RATE = 0.0006280291441834253
Using learning rate = 0.0006280291441834253

[TrackingCallback] Mean Epoch Time = 0.26406660079956057 seconds, Total Train Time = 14.592645168304443
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.6527805328369141, 'eval_runtime': 0.4967, 'eval_samples_per_second': 10398.53, 'eval_steps_per_second': 163.075, 'epoch': 15.0}
(5165, 96, 6)

 99%|█████████▉| 137/138 [37:19<00:16, 16.57s/it]INFO:p-995201:t-139381727305856:get_model.py:get_model:Loading model from: ibm-granite/granite-timeseries-ttm-r2

Saved results to: ttm_finetuning_results_mase/site_5541_Mayaganj_Bhagalpur_BSPCB_15Min_metrics.json

============================================================
Processing: site_1560_Bawana_Delhi_DPCC_15Min.csv
============================================================
-------------------- Running few-shot 5% --------------------

INFO:p-995201:t-139381727305856:get_model.py:get_model:Model loaded successfully from ibm-granite/granite-timeseries-ttm-r2, revision = main.
INFO:p-995201:t-139381727305856:get_model.py:get_model:[TTM] context_length = 512, prediction_length = 96
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Running learning rate (LR) finder algorithm. If the suggested LR is very low, we suggest setting the LR manually.
INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Using cuda:0.

Number of params before freezing backbone 805280
Number of params after freezing the backbone 289696

INFO:p-995201:t-139381727305856:lr_finder.py:optimal_lr_finder:LR Finder: Suggested learning rate = 0.000756463327554629

OPTIMAL SUGGESTED LEARNING RATE = 0.000756463327554629
Using learning rate = 0.000756463327554629

[TrackingCallback] Mean Epoch Time = 0.24540333314375443 seconds, Total Train Time = 8.473771095275879
++++++++++++++++++++ Test MSE after few-shot 5% fine-tuning ++++++++++++++++++++

{'eval_loss': 0.510363757610321, 'eval_runtime': 0.5391, 'eval_samples_per_second': 9580.021, 'eval_steps_per_second': 150.238, 'epoch': 11.0}
(5165, 96, 6)

100%|██████████| 138/138 [37:33<00:00, 16.33s/it]

Saved results to: ttm_finetuning_results_mase/site_1560_Bawana_Delhi_DPCC_15Min_metrics.json

============================================================
All results saved to: ttm_finetuning_results_mase/all_sites_metrics_20260224_144848.json
============================================================